app/main/default/objects/OAH_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Division</field>
                <operation>equals</operation>
                <value>OAH</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>OAH_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

app/main/default/objects/OAH_Task__c/fields/From__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OAH_Tasks1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

app/main/default/classes/OAHTaskSharingTest.cls
@isTest
private class OAHTaskSharingTest {

    @testSetup static void setupTestData() {
        UserRole r = new UserRole(DeveloperName = 'MyCustomRole', Name = 'My Role');
        insert r;
        User u1 = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'mpadgett@dcca.hawaii.gov',
            Username = 'User1@idontknow.com',
            Alias = 'User1',
            EmailEncodingKey = 'ISO-8859-1',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            UserRoleId = r.Id);
        insert u1;
        User u2 = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User'].Id,
            LastName = 'last',
            Email = 'mpadgett@dcca.hawaii.gov',
            Username = 'User2@idontknow.com',
            Alias = 'User2',
            EmailEncodingKey = 'ISO-8859-1',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            UserRoleId = r.Id);
        insert u2;
    }
    
    @isTest static void TestTaskAssigned() {
        Test.startTest();
        User u1 = [SELECT Id from User where Alias = 'User1'];
        User u2 = [SELECT Id from User where Alias = 'User2'];
        OAH_Task__c OAHTask = new OAH_Task__c(Assigned_To__c = u1.Id, From__c = u2.Id);
        insert OAHTask;
        Test.stopTest();
    }

}