app/main/default/objects/OAH_Case_List__c/fields/Case_Name__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <inlineHelpText>Case Name is a free-form description of the case.  Case Number generally follows one of the following formats:  Board-Year-Number (CLB-2019-001) or Board-Type-Year-Number (CLB-LIC-2019-001).  Do not specify sequential number if it is to be auto-generated.</inlineHelpText>
        <label>Case Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

app/main/default/objects/OAH_Case_List__c/fields/Date_Filed__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Date_Filed__c</fullName>
        <label>Date Filed</label>
        <type>Date</type>
    </fields>
</CustomObject>

app/main/default/objects/OAH_Case_List__c/fields/Fee_Required__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Fee_Required__c</fullName>
        <label>Fee Required</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                    <default>true</default>
                    <label>N/A</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Outstanding</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

app/main/default/classes/OAHcapitalizeNameTest.cls
@isTest
private class OAHcapitalizeNameTest {
    static testMethod void capNameTest() {
        // Create Case Name for test
        OAH_Case_List__c newCase = new OAH_Case_List__c();
        newCase.Name = 'testname';
        newCase.Case_Name__c = 'test';
        newCase.Date_Filed__c = system.today();
        newCase.Fee_Required__c = 'Paid';
        Test.startTest();
        insert newCase;
        Test.stopTest();
        
        List<OAH_Case_List__c> caseList = [SELECT Name from OAH_Case_List__c WHERE Name = 'TESTNAME'];
        system.assertEquals(1,caseList.size());
    }
}