app/main/default/objects/OAH_Case_Creation_Board__c/OAH_Case_Creation_Board__c.object-meta.xml
<CustomObject>
    <description>Boards where OAH will create the Case Number, as opposed to it being created prior to OAH receiving it.</description>
    <fields>
        <fullName>Board__c</fullName>
        <description>Boards listed here will result in OAH being able to create a new Case Number</description>
        <inlineHelpText>When creating cases, cases prefixed by these boards will auto-generate the next available sequential number.
examples:  PDH, ACC-LIC, *-LIC</inlineHelpText>
        <label>Board</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sequential_Number_Length__c</fullName>
        <inlineHelpText>The length of the auto-generated sequential number.  A length of 3 with a generated value of 1 will appear as &apos;-001&apos; in the Case Number.</inlineHelpText>
        <label>Sequential Number Length</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OAH Case Creation Board</label>
    <listViews>
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>Board__c</columns>
        <columns>Sequential_Number_Length__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews>
    <nameField>
        <label>OAH Case Creation Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAH Case Creation Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

app/main/default/objects/OAH_Case_Creation_Board__c/fields/Board__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <description>Boards listed here will result in OAH being able to create a new Case Number</description>
        <inlineHelpText>When creating cases, cases prefixed by these boards will auto-generate the next available sequential number.
examples:  PDH, ACC-LIC, *-LIC</inlineHelpText>
        <label>Board</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

app/main/default/objects/OAH_Case_Creation_Board__c/fields/Sequential_Number_Length__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Sequential_Number_Length__c</fullName>
        <inlineHelpText>The length of the auto-generated sequential number.  A length of 3 with a generated value of 1 will appear as &apos;-001&apos; in the Case Number.</inlineHelpText>
        <label>Sequential Number Length</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

app/main/default/objects/OAH_Case_List__c/fields/Case_Name__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <inlineHelpText>Case Name is a free-form description of the case.  Case Number generally follows one of the following formats:  Board-Year-Number (CLB-2019-001) or Board-Type-Year-Number (CLB-LIC-2019-001).  Do not specify sequential number if it is to be auto-generated.</inlineHelpText>
        <label>Case Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

app/main/default/objects/OAH_Case_List__c/fields/Case_Phase__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Case_Phase__c</fullName>
        <label>Case Phase</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Intake</fullName>
                    <default>true</default>
                    <label>Intake</label>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Hearing</fullName>
                </value>
                <value>
                    <fullName>Appeal</fullName>
                </value>
                <value>
                    <fullName>Remand</fullName>
                </value>
                <value>
                    <fullName>Not Appealed</fullName>
                </value>
                <value>
                    <fullName>Close Case</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

app/main/default/objects/OAH_Case_List__c/fields/Case_Status__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Case_Status__c</fullName>
        <defaultValue>&quot;Open&quot;</defaultValue>
        <label>Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Re-Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

app/main/default/objects/OAH_Case_List__c/fields/Case_Type__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_Agency__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Appeal</fullName>
                </value>
                <value>
                    <fullName>Cease &amp; Desist</fullName>
                </value>
                <value>
                    <fullName>Citation</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>Dec Relief</fullName>
                </value>
                <value>
                    <fullName>Disability Benefits</fullName>
                </value>
                <value>
                    <fullName>Disciplinary</fullName>
                </value>
                <value>
                    <fullName>LC</fullName>
                </value>
                <value>
                    <fullName>Lic Den</fullName>
                </value>
                <value>
                    <fullName>License-Other</fullName>
                </value>
                <value>
                    <fullName>OSC</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PIP</fullName>
                </value>
                <value>
                    <fullName>Retirement Benefits</fullName>
                </value>
                <value>
                    <fullName>SM</fullName>
                </value>
                <value>
                    <fullName>TM</fullName>
                </value>
                <value>
                    <fullName>TN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

app/main/default/objects/OAH_Case_List__c/fields/Date_Filed__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Date_Filed__c</fullName>
        <label>Date Filed</label>
        <type>Date</type>
    </fields>
</CustomObject>

app/main/default/objects/OAH_Case_List__c/fields/Division_Agency__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Division_Agency__c</fullName>
        <label>Division-Agency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BREG</fullName>
                </value>
                <value>
                    <fullName>CAAP</fullName>
                </value>
                <value>
                    <fullName>DFI</fullName>
                </value>
                <value>
                    <fullName>ERS</fullName>
                </value>
                <value>
                    <fullName>EUTF</fullName>
                </value>
                <value>
                    <fullName>HCDA</fullName>
                </value>
                <value>
                    <fullName>HPEAP</fullName>
                </value>
                <value>
                    <fullName>INS</fullName>
                </value>
                <value>
                    <fullName>PDH</fullName>
                </value>
                <value>
                    <fullName>PUC</fullName>
                </value>
                <value>
                    <fullName>PVL</fullName>
                </value>
                <value>
                    <fullName>RICO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

app/main/default/objects/OAH_Case_List__c/fields/Fee_Required__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Fee_Required__c</fullName>
        <label>Fee Required</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                    <default>true</default>
                    <label>N/A</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Outstanding</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

app/main/default/classes/OAHCaseNumberGeneratorTest.cls
@isTest
private class OAHCaseNumberGeneratorTest {
    static testMethod void CaseNbrGenTest() {
        // Trigger will be tested on OAH_Case_List__c insert, but create other records here
        List<OAH_Case_Creation_Board__c> lstBoard = new List<OAH_Case_Creation_Board__c>();
        OAH_Case_Creation_Board__c newBoard;
        newBoard = new OAH_Case_Creation_Board__c(name='Procurement Decisions and Hearings',Board__c='PDH',Sequential_Number_Length__c=3);
        lstBoard.add(newBoard);
        newBoard = new OAH_Case_Creation_Board__c(name='Licensing Cases',Board__c='*-LIC',Sequential_Number_Length__c=3);
        lstBoard.add(newBoard);
        newBoard = new OAH_Case_Creation_Board__c(name='ACC Only Licensing Cases',Board__c='ACC-LIC',Sequential_Number_Length__c=3);
        lstBoard.add(newBoard);
        insert lstBoard;
        
        Test.startTest();
        OAH_Case_List__c newCase = new OAH_Case_List__c();
        newCase.Name = 'PDH';
        newCase.Case_Name__c = 'Test Case';
        newCase.Division_Agency__c = 'PDH';
        newCase.Case_Type__c = 'NEW';
        newCase.Case_Phase__c = 'Intake';
        newCase.Case_Status__c = 'Open';
        newCase.Date_Filed__c = system.today();
        newCase.Fee_Required__c = 'Paid';
        insert newCase;

        OAH_Case_List__c newCase2 = new OAH_Case_List__c();
        newCase2.Name = 'PDH-2020';
        newCase2.Case_Name__c = 'Test Case';
        newCase2.Division_Agency__c = 'PDH';
        newCase2.Case_Type__c = 'NEW';
        newCase2.Case_Phase__c = 'Intake';
        newCase2.Case_Status__c = 'Open';
        newCase2.Date_Filed__c = system.today();
        newCase2.Fee_Required__c = 'Paid';
        insert newCase2;

        OAH_Case_List__c newCase3 = new OAH_Case_List__c();
        newCase3.Name = 'PDH-2020-003';
        newCase3.Case_Name__c = 'Test Case';
        newCase3.Division_Agency__c = 'PDH';
        newCase3.Case_Type__c = 'NEW';
        newCase3.Case_Phase__c = 'Intake';
        newCase3.Case_Status__c = 'Open';
        newCase3.Date_Filed__c = system.today();
        newCase3.Fee_Required__c = 'Paid';
        insert newCase3;

        // Modify previous case to contain '-P' suffix then generate new case #
        newCase3.Name = 'PDH-2020-003-P';
        update newCase3;

        OAH_Case_List__c newCase4 = new OAH_Case_List__c();
        newCase4.Name = 'PDH-2020';
        newCase4.Case_Name__c = 'Test Case';
        newCase4.Division_Agency__c = 'PDH';
        newCase4.Case_Type__c = 'NEW';
        newCase4.Case_Phase__c = 'Intake';
        newCase4.Case_Status__c = 'Open';
        newCase4.Date_Filed__c = system.today();
        newCase4.Fee_Required__c = 'Paid';
        insert newCase4;
        
        Test.stopTest();
        
        List<OAH_Case_Creation_Board__c> boardList = [SELECT Board__c from OAH_Case_Creation_Board__c WHERE Board__c = 'PDH'];
        system.assertEquals(1, boardList.size());
        
        List<OAH_Case_List__c> caseList = [SELECT Name from OAH_Case_List__c WHERE Name like 'PDH%'];
        system.assertEquals(4, caseList.size());
    }
}