app/main/default/objects/OAH_Case_Creation_Board__c/OAH_Case_Creation_Board__c.object-meta.xml
<CustomObject>
    <description>Boards where OAH will create the Case Number, as opposed to it being created prior to OAH receiving it.</description>
    <fields>
        <fullName>Board__c</fullName>
        <description>Boards listed here will result in OAH being able to create a new Case Number</description>
        <inlineHelpText>When creating cases, cases prefixed by these boards will auto-generate the next available sequential number.
examples:  PDH, ACC-LIC, *-LIC</inlineHelpText>
        <label>Board</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sequential_Number_Length__c</fullName>
        <inlineHelpText>The length of the auto-generated sequential number.  A length of 3 with a generated value of 1 will appear as &apos;-001&apos; in the Case Number.</inlineHelpText>
        <label>Sequential Number Length</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OAH Case Creation Board</label>
    <listViews>
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>Board__c</columns>
        <columns>Sequential_Number_Length__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews>
    <nameField>
        <label>OAH Case Creation Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAH Case Creation Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

app/main/default/objects/OAH_Case_Creation_Board__c/fields/Board__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <description>Boards listed here will result in OAH being able to create a new Case Number</description>
        <inlineHelpText>When creating cases, cases prefixed by these boards will auto-generate the next available sequential number.
examples:  PDH, ACC-LIC, *-LIC</inlineHelpText>
        <label>Board</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

app/main/default/objects/OAH_Case_Creation_Board__c/fields/Sequential_Number_Length__c.field-meta.xml
<CustomObject>
    <fields>
        <fullName>Sequential_Number_Length__c</fullName>
        <inlineHelpText>The length of the auto-generated sequential number.  A length of 3 with a generated value of 1 will appear as &apos;-001&apos; in the Case Number.</inlineHelpText>
        <label>Sequential Number Length</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

app/main/default/classes/OAHAccessCaseCreationBoardTest.cls
@isTest
private class OAHAccessCaseCreationBoardTest {
    static testMethod void TestCreateAccess() {
        //Select user by alias
        User u1 = [SELECT Id FROM User WHERE
                   Id in ( SELECT AssigneeId FROM PermissionSetAssignment
                           WHERE PermissionSet.Name = 'OAH_Admin') Limit 1];
        
        //Run As user specified
        System.RunAs(u1){
        
            OAH_Case_Creation_Board__c OAHObj = new OAH_Case_Creation_Board__c(Board__c = 'PDH', Sequential_Number_Length__c = 3);
            Test.startTest();
            
            System.debug('Testing create access to OAH_Case_Creation_Board for user ' + u1);
            try {
                insert OAHObj;
            } catch (DmlException e) {
                System.assertEquals('No access to obj OAH_Case_Creation_Board__c for OAH_Admin permission set', 
                                     e.getDmlStatusCode(0));
            }
            Test.stopTest();
        
            List<OAH_Case_Creation_Board__c> boardList = [SELECT Board__c from OAH_Case_Creation_Board__c];
            system.assertEquals(1, boardList.size());
              }
    }
}